""" Handle Private Data from Account Owner """
""" BITSO API """
API_KEY = "xxxxx"
API_SECRET = "XXXXXXXXXXXXXXXXXXX"

""" Bank API """

CLABE = "000000000000000000"
WALLET_AUTOMATIC_SELL = "ABCXXXXXXXXXXXXXXXXX"
FIRST_NAMES = "xxxxx"
LAST_NAMES = "xxxxx"
NOTES_REF = "xx1"
NUMERIC_REF = "1234"
